# Generated by Django 5.0.4 on 2024-06-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Izvodjac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=31)),
            ],
            options={
                'db_table': 'izvodjac',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnicko_ime', models.CharField(max_length=31)),
                ('sifra', models.CharField(max_length=255)),
                ('ime', models.CharField(max_length=31)),
                ('prezime', models.CharField(max_length=31)),
                ('tip', models.CharField(max_length=1)),
                ('pitanje_lozinka', models.CharField(max_length=255)),
                ('odgovor_lozinka', models.CharField(max_length=255)),
                ('rang_poeni', models.IntegerField(null=True)),
                ('licni_poeni', models.IntegerField(null=True)),
                ('poslednja_aktivnost', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'korisnik',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=31)),
            ],
            options={
                'db_table': 'zanr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pesma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=63)),
                ('izv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblankspace.izvodjac')),
            ],
            options={
                'db_table': 'pesma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Predlaze_Pesmu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_pesme', models.CharField(max_length=63)),
                ('izv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblankspace.izvodjac')),
                ('kor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblankspace.korisnik')),
            ],
            options={
                'db_table': 'predlaze_pesmu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Soba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poeni_1', models.IntegerField()),
                ('poeni_2', models.IntegerField(null=True)),
                ('poeni_runde_1', models.CharField(max_length=31, null=True)),
                ('poeni_runde_2', models.CharField(max_length=31, null=True)),
                ('stihovi', models.CharField(max_length=63)),
                ('kor_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soba_kor_1', to='appblankspace.korisnik')),
                ('kor_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soba_kor_2', to='appblankspace.korisnik')),
            ],
            options={
                'db_table': 'soba',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stihovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivo', models.CharField(max_length=1)),
                ('poznat_tekst', models.CharField(max_length=255)),
                ('nepoznat_tekst', models.CharField(max_length=255)),
                ('zvuk', models.FilePathField()),
                ('pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblankspace.pesma')),
            ],
            options={
                'db_table': 'stihovi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Predlaze_Izvodjaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_izvodjaca', models.CharField(max_length=31)),
                ('kor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblankspace.korisnik')),
                ('zan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblankspace.zanr')),
            ],
            options={
                'db_table': 'predlaze_izvodjaca',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='izvodjac',
            name='zan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblankspace.zanr'),
        ),
    ]
